version: 2

sources:
  - name: staging
    schema: public
    tables:
      - name: listen_events
      - name: page_view_events
      - name: auth_events
      - name: songs
      - name: state_codes
